// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpD6xMVL3flsDbYpr2ZBTN6GhkF_8XnDk',
    appId: '1:439114528129:web:d759b6aea5b86f19516480',
    messagingSenderId: '439114528129',
    projectId: 'prototype-a-42c03',
    authDomain: 'prototype-a-42c03.firebaseapp.com',
    storageBucket: 'prototype-a-42c03.firebasestorage.app',
    measurementId: 'G-6NVSPD71TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfb8663-acY2ahw0-7p7qfwu2GSsAW4Uc',
    appId: '1:439114528129:android:188de3f4a82e9afa516480',
    messagingSenderId: '439114528129',
    projectId: 'prototype-a-42c03',
    storageBucket: 'prototype-a-42c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmsLLwDzjiRPr9oeI0IK78e2Iw5GkWhaM',
    appId: '1:439114528129:ios:5ce0855106acfde4516480',
    messagingSenderId: '439114528129',
    projectId: 'prototype-a-42c03',
    storageBucket: 'prototype-a-42c03.firebasestorage.app',
    iosBundleId: 'com.example.prototypea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmsLLwDzjiRPr9oeI0IK78e2Iw5GkWhaM',
    appId: '1:439114528129:ios:5ce0855106acfde4516480',
    messagingSenderId: '439114528129',
    projectId: 'prototype-a-42c03',
    storageBucket: 'prototype-a-42c03.firebasestorage.app',
    iosBundleId: 'com.example.prototypea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpD6xMVL3flsDbYpr2ZBTN6GhkF_8XnDk',
    appId: '1:439114528129:web:7869914b396091d1516480',
    messagingSenderId: '439114528129',
    projectId: 'prototype-a-42c03',
    authDomain: 'prototype-a-42c03.firebaseapp.com',
    storageBucket: 'prototype-a-42c03.firebasestorage.app',
    measurementId: 'G-G8RQM7BGEK',
  );
}
